Repository dev-memento/memento-api, pull requests merged in 2025-03, with the labels that each got.

#36 [FEAT] 스케줄 롬복 적용 및 태그 관계 수정
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiController.java
  src/main/java/com/official/memento/schedule/conntroller/dto/response/AllDaySchedulesResponse.java
  src/main/java/com/official/memento/schedule/conntroller/dto/response/ScheduleDetailResponse.java
  src/main/java/com/official/memento/schedule/domain/ScheduleTagRepository.java
  src/main/java/com/official/memento/schedule/domain/entity/Schedule.java
  src/main/java/com/official/memento/schedule/domain/entity/ScheduleTag.java
  src/main/java/com/official/memento/schedule/infrastructure/ScheduleRepositoryAdapter.java
  src/main/java/com/official/memento/schedule/infrastructure/ScheduleTagRepositoryAdapter.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleEntity.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleEntityJpaRepository.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleTagEntity.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleTagEntityJpaRepository.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/projection/ScheduleOrderInfoProjection.java
  src/main/java/com/official/memento/schedule/service/ScheduleService.java
  src/main/java/com/official/memento/schedule/service/command/RepeatScheduleCreateCommand.java
  src/main/java/com/official/memento/schedule/service/command/ScheduleCreateCommand.java
  src/main/java/com/official/memento/schedule/service/command/ScheduleUpdateGroupCommand.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleCreateUseCase.java
Labels: enhancement

#40 [CHORE] 스케줄 리팩토링 사항 반영
  src/main/java/com/official/memento/orderinfo/domain/OrderInfoRepository.java
  src/main/java/com/official/memento/orderinfo/infrastructure/OrderInfoRepositoryAdapter.java
  src/main/java/com/official/memento/orderinfo/infrastructure/persistence/OrderInfoEntityJpaRepository.java
  src/main/java/com/official/memento/orderinfo/service/OrderInfoService.java
  src/main/java/com/official/memento/orderinfo/service/usecase/OrderInfoCreateUseCase.java
  src/main/java/com/official/memento/orderinfo/service/usecase/OrderInfoDeleteUseCase.java
  src/main/java/com/official/memento/orderinfo/service/usecase/OrderInfoGetUseCase.java
  src/main/java/com/official/memento/schedule/conntroller/dto/response/AllDaySchedulesResponse.java
  src/main/java/com/official/memento/schedule/conntroller/dto/response/ScheduleDetailResponse.java
  src/main/java/com/official/memento/schedule/service/ScheduleService.java
  src/main/java/com/official/memento/schedule/service/command/RepeatScheduleCreateCommand.java
Labels: chore

#45 [FEAT] 애플 스케줄 생성 및 동기화
  src/main/java/com/official/memento/auth/service/AuthService.java
  src/main/java/com/official/memento/global/exception/DataBaseIntegrityException.java
  src/main/java/com/official/memento/global/exception/ErrorCode.java
  src/main/java/com/official/memento/global/handler/GlobalExceptionHandler.java
  src/main/java/com/official/memento/member/domain/MemberSyncInfo.java
  src/main/java/com/official/memento/member/domain/port/MemberSyncInfoRepository.java
  src/main/java/com/official/memento/member/infrastructure/MemberSyncInfoRepositoryAdapter.java
  src/main/java/com/official/memento/member/infrastructure/persistence/MemberSyncInfoEntity.java
  src/main/java/com/official/memento/member/infrastructure/persistence/entity/MemberPersonalInfoEntity.java
  src/main/java/com/official/memento/member/infrastructure/persistence/entity/MemberSyncInfoEntity.java
  src/main/java/com/official/memento/member/infrastructure/persistence/repository/MemberSyncInfoEntityJpaRepository.java
  src/main/java/com/official/memento/member/service/MemberPersonalInfoService.java
  src/main/java/com/official/memento/member/service/MemberSyncInfoService.java
  src/main/java/com/official/memento/member/service/command/MemberSyncInfoCreateCommand.java
  src/main/java/com/official/memento/member/service/command/MemberSyncInfoGetUseCase.java
  src/main/java/com/official/memento/member/service/usecase/MemberSyncInfoCreateUseCase.java
  src/main/java/com/official/memento/member/service/usecase/MemberSyncInfoUpdateUseCase.java
  src/main/java/com/official/memento/orderinfo/service/OrderInfoService.java
  src/main/java/com/official/memento/orderinfo/service/usecase/OrderInfoCreateUseCase.java
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiController.java
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiDocs.java
  src/main/java/com/official/memento/schedule/conntroller/dto/request/AppleScheduleRequest.java
  src/main/java/com/official/memento/schedule/conntroller/dto/request/AppleSchedulesCreateRequest.java
  src/main/java/com/official/memento/schedule/conntroller/dto/request/AppleSchedulesRequest.java
  src/main/java/com/official/memento/schedule/domain/ScheduleRepository.java
  src/main/java/com/official/memento/schedule/domain/entity/ScheduleVo.java
  src/main/java/com/official/memento/schedule/infrastructure/ScheduleRepositoryAdapter.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleEntityJpaRepository.java
  src/main/java/com/official/memento/schedule/service/ScheduleService.java
  src/main/java/com/official/memento/schedule/service/command/AppleScheduleCreateCommand.java
  src/main/java/com/official/memento/schedule/service/command/AppleSchedulesCommand.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleCreateUseCase.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleGroupCreateUseCase.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleGroupDeleteUseCase.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleGroupUpdateUseCase.java
  src/main/java/com/official/memento/tag/infrastructure/TagRepositoryAdapter.java
  src/main/java/com/official/memento/tag/infrastructure/persistence/TagJpaRepository.java
  src/main/java/com/official/memento/tag/service/TagGetUseCase.java
  src/main/java/com/official/memento/tag/service/TagService.java
Labels: enhancement

#48 chore: 멤버 아이디 제거
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiController.java
Labels: bug

#49 chore: 투두에 태그 정보 포함
  src/main/java/com/official/memento/todo/service/ToDoQueryService.java
Labels: bug

#44 [CHORE] 스케줄 순서 할당 로직 수정
  src/main/java/com/official/memento/orderinfo/service/OrderInfoService.java
  src/main/java/com/official/memento/schedule/service/ScheduleService.java
Labels: chore

#53 [FEAT] 연동정보 불러오기 기능 구현및 연동 관련 인자들 추가
  src/main/java/com/official/memento/auth/controller/AuthApiController.java
  src/main/java/com/official/memento/auth/controller/AuthApiDocs.java
  src/main/java/com/official/memento/auth/controller/dto/AuthApiRequest.java
  src/main/java/com/official/memento/auth/service/AuthResult.java
  src/main/java/com/official/memento/auth/service/AuthService.java
  src/main/java/com/official/memento/auth/service/result/AuthResult.java
  src/main/java/com/official/memento/auth/service/result/NewAuthResult.java
  src/main/java/com/official/memento/auth/service/usecase/AuthenticateUseCase.java
  src/main/java/com/official/memento/auth/service/usecase/ExtractRefreshTokenUseCase.java
  src/main/java/com/official/memento/auth/service/usecase/RefreshTokenUseCase.java
  src/main/java/com/official/memento/member/controller/MemberPersonalInfoApiController.java
  src/main/java/com/official/memento/member/controller/MemberPersonalInfoApiDocs.java
  src/main/java/com/official/memento/member/controller/MemberSyncInfoApiController.java
  src/main/java/com/official/memento/member/controller/MemberSyncInfoApiDocs.java
  src/main/java/com/official/memento/member/controller/dto/MemberSyncInfoDto.java
  src/main/java/com/official/memento/member/controller/dto/MemberUptimeDto.java
  src/main/java/com/official/memento/member/service/MemberSyncInfoService.java
  src/main/java/com/official/memento/member/service/command/MemberSyncInfoGetUseCase.java
  src/main/java/com/official/memento/member/service/result/MemberPersonalInfoResult.java
  src/main/java/com/official/memento/member/service/result/MemberSyncInfoResult.java
  src/main/java/com/official/memento/member/service/usecase/MemberSyncInfoCreateUseCase.java
  src/main/java/com/official/memento/schedule/conntroller/ScheduleApiController.java
  src/main/java/com/official/memento/schedule/service/ScheduleService.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleCreateUseCase.java
Labels: enhancement

#59 [FEAT] 구글 스케줄 동기화 구현
  src/main/java/com/official/memento/auth/infrastructure/apple/AppleAuthClientAdapter.java
  src/main/java/com/official/memento/auth/infrastructure/apple/RestClientConfig.java
  src/main/java/com/official/memento/auth/infrastructure/google/GoogleAuthClientAdapter.java
  src/main/java/com/official/memento/auth/infrastructure/google/GoogleTokenResponse.java
  src/main/java/com/official/memento/global/config/RestClientConfig.java
  src/main/java/com/official/memento/global/exception/ErrorCode.java
  src/main/java/com/official/memento/member/domain/MemberSyncInfo.java
  src/main/java/com/official/memento/member/infrastructure/MemberSyncInfoRepositoryAdapter.java
  src/main/java/com/official/memento/member/infrastructure/persistence/entity/MemberSyncInfoEntity.java
  src/main/java/com/official/memento/member/service/MemberSyncInfoService.java
  src/main/java/com/official/memento/member/service/result/MemberSyncInfoResult.java
  src/main/java/com/official/memento/member/service/usecase/MemberSyncInfoUpdateUseCase.java
  src/main/java/com/official/memento/orderinfo/service/OrderInfoService.java
  src/main/java/com/official/memento/schedule/controller/ScheduleApiController.java
  src/main/java/com/official/memento/schedule/controller/dto/request/ScheduleUpdateRequest.java
  src/main/java/com/official/memento/schedule/domain/ScheduleRepository.java
  src/main/java/com/official/memento/schedule/domain/entity/Schedule.java
  src/main/java/com/official/memento/schedule/infrastructure/ScheduleRepositoryAdapter.java
  src/main/java/com/official/memento/schedule/infrastructure/google/GoogleCalendarAdapter.java
  src/main/java/com/official/memento/schedule/infrastructure/google/GoogleCalendarEvent.java
  src/main/java/com/official/memento/schedule/infrastructure/google/GoogleCalendarResponse.java
  src/main/java/com/official/memento/schedule/infrastructure/google/GoogleCalendarUpdateRequest.java
  src/main/java/com/official/memento/schedule/infrastructure/google/StartEnd.java
  src/main/java/com/official/memento/schedule/infrastructure/persistence/ScheduleEntityJpaRepository.java
  src/main/java/com/official/memento/schedule/service/ScheduleResult.java
  src/main/java/com/official/memento/schedule/service/ScheduleService.java
  src/main/java/com/official/memento/schedule/service/command/ScheduleUpdateCommand.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleCreateUseCase.java
  src/main/java/com/official/memento/schedule/service/usecase/ScheduleUpdateUseCase.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: enhancement

#65 [FIX] 스케줄 업데이트 로직
  src/main/java/com/official/memento/schedule/service/ScheduleService.java
Labels: bug

#63 [FEAT] 멤버에 시간대 적용
  src/main/java/com/official/memento/auth/controller/AuthApiController.java
  src/main/java/com/official/memento/auth/controller/dto/AuthApiRequest.java
  src/main/java/com/official/memento/auth/service/AuthService.java
  src/main/java/com/official/memento/auth/service/command/AuthCommand.java
  src/main/java/com/official/memento/member/controller/MemberPersonalInfoApiController.java
  src/main/java/com/official/memento/member/controller/dto/MemberTimeZoneUpdateRequest.java
  src/main/java/com/official/memento/member/domain/MemberPersonalInfo.java
  src/main/java/com/official/memento/member/infrastructure/MemberPersonalInfoRepositoryAdapter.java
  src/main/java/com/official/memento/member/infrastructure/persistence/MemberPersonalInfoMapper.java
  src/main/java/com/official/memento/member/infrastructure/persistence/entity/MemberPersonalInfoEntity.java
  src/main/java/com/official/memento/member/service/MemberPersonalInfoService.java
  src/main/java/com/official/memento/member/service/command/MemberPersonalInfoCreateCommand.java
  src/main/java/com/official/memento/member/service/command/MemberTimeZoneUpdateCommand.java
  src/main/java/com/official/memento/member/service/usecase/MemberPersonalInfoGetUseCase.java
  src/main/java/com/official/memento/member/service/usecase/MemberPersonalInfoUpdateUseCase.java
Labels: enhancement
